AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bedrock-image-gen

  Sample SAM Template for bedrock-image-gen

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  BedrockImageGenFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: bedrock_image_gen_function
      CodeUri: bedrock_image_gen_function/
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 1024
      Architectures:
        - x86_64
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/my-lambda-bedrock-s3-role
      Events:
        BedRockImageGen:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /imagegen
            Method: get

Outputs:
  BedrockImageGenFunction:
    Value: !GetAtt BedrockImageGenFunction.Arn

